nodeLinker: node-modules
enableGlobalCache: true

# Make JupyterLab 3 testutils accept React 18
# Remove during JupyterLab 4 upgrade
packageExtensions:
  "@jupyterlab/testutils@^3.0.0":
    peerDependencies:
      "react": ">=17.0.0 <19.0.0"
      "react-dom": ">=17.0.0 <19.0.0"
