nodeLinker: node-modules

packageExtensions:
  "@jupyterlab/apputils@*":
    dependencies:
      "@jupyterlab/coreutils": "^5.2.0"
  "@jupyterlab/services@*":
    dependencies:
      "@lumino/widgets": "^1.40.0"

resolutions:
  "@jupyterlab/apputils": "^3.6.0"
  "@jupyterlab/coreutils": "^5.2.0"
  "@jupyterlab/services": "^6.5.0"
  "@jupyterlab/builder": "3.3.0"
