nodeLinker: node-modules
enableGlobalCache: true

enableImmutableInstalls: false
enableInlineBuilds: false
enableTelemetry: false
httpTimeout: 60000

logFilters:
  - code: YN0006  # Uses deprecated option
    level: discard
  - code: YN0007  # Multiple versions of same package
    level: discard
  - code: YN0008  # Unused dependencies
    level: discard
  - code: YN0013  # Resolution issues
    level: discard
  - code: YN0019  # Workspace dependency issues
    level: discard

npmRegistryServer: "https://registry.yarnpkg.com"

# Make JupyterLab 3 testutils accept React 18
# Remove during JupyterLab 4 upgrade
packageExtensions:
  "@jupyterlab/testutils@^3.0.0":
    peerDependencies:
      "react": ">=17.0.0 <19.0.0"
      "react-dom": ">=17.0.0 <19.0.0"
