nodeLinker: node-modules

resolutions:
  "@jupyterlab/apputils": "^4.5.0"
  "@jupyterlab/coreutils": "^6.4.0"
  "@jupyterlab/services": "^7.4.0"
  "@jupyterlab/builder": "4.0.0"
  "@lumino/widgets": "^2.0.0"
