#!/usr/bin/env bash
#
# Binder postBuild instructions
set -eux
yarn install
yarn run build
python -m pip install .

# !! Be sure the version of jupyterlab-tour matches the one saved in bind/workspace.json
jupyter labextension install jupyterlab-tour@^2.1.1 @jupyterlab/server-proxy --no-build
jupyter labextension link packages/common/ packages/labextension --no-build
jupyter lab build --minimize=False

# Import the workspace into JupyterLab
jupyter lab workspaces import binder/workspace.json

mkdir -p $HOME/.jupyter/
cp binder/jupyter_notebook_config.py ${HOME}/.jupyter/
